# fly.toml app configuration file generated for server-frosty-field-8912 on 2025-07-07T10:57:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-frosty-field-8912'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
